title: Max Chadwick
url: https://maxchadwick.xyz
permalink: /blog/:title
markdown: kramdown
paginate: 6
paginate_path: "/blog/page/:num/"

defaults:
  -
    scope:
      path: "blog/page"
    values:
      sitemap: false

author: "Max Chadwick"
twitter:
  username: maxpchadwick

author: maxpchadwick

collections:
  - projects

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - octopress-autoprefixer
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jemoji

excerpt_separator: <!-- excerpt_separator -->

ga:
  prod: UA-24185213-7
  dev: UA-24185213-9

pre-commit:
  - check: FrontMatterVariableExists
    variables: ['description']
  - check: FrontMatterVariableIsNotDuplicate
    variables: ['description']
  - check: FrontMatterVariableMeetsLengthRequirements
    variables: ['description||165', 'title||100']
  - check: NoDuplicateTags
